In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale

In [4]:
df_sum=pd.read_excel('df_sum2.xlsx')

In [6]:
df_sum.drop('Unnamed: 0.1',axis=1,inplace=True)

In [7]:
df_sum

Unnamed: 0       reg  Year  divorce_rate  regional_gdp     consume  \
0             0       北京市  2018      3.427825      33105.97  102.488458   
1             1       天津市  2018      4.111147      13362.92  101.950745   
2             2       上海市  2018      2.438029      36011.82  101.588254   
3             3       重庆市  2018      4.963452      21588.80  102.047067   
4             4       河北省  2018      3.110862      32494.61  102.448942   
..          ...       ...   ...           ...           ...         ...   
336         336       陕西省  2008           NaN       7314.58  106.359070   
337         337       甘肃省  2008           NaN       3166.82  108.209650   
338         338       青海省  2008           NaN       1018.62  110.086500   
339         339   宁夏回族自治区  2008           NaN       1203.92  108.480960   
340         340  新疆维吾尔自治区  2008           NaN       4183.21  108.055790   

     illteracy  sample_pop      density      highedu  birth  family_peoplenum  \
0        268.0     15823.0  1135.527118  5268.000000   8.24           16773.0   
1        159.0     11480.0  5016.304411  4150.000000   6.67           11278.0   
2        426.0     17922.0  3822.695371  3517.000000   7.20           19368.0   
3        808.0     21113.0  2026.424731  3081.000000  11.02           24920.0   
4       1994.0     50466.0  3210.355015  2457.000000  11.26           61115.0   
..         ...         ...          ...          ...    ...               ...   
336     2326.0     28407.0  5488.000000  2879.911953  10.29           33636.0   
337     3349.0     18840.0  3802.000000  1686.836072  13.22           23717.0   
338      654.0      3919.0  2051.000000  1033.242754  14.49            4963.0   
339      430.0      4267.0   883.000000  1610.245902  14.31            5520.0   
340      698.0     15026.0  4987.000000  1413.727924  16.05           18955.0   

     family_num   House_Price  tertiary_gdp  raising_rate  sex_ratio  
0        6769.0  37420.188541      27508.06         13.37      98.75  
1        4529.0  15924.260523       8352.32         13.03     115.72  
2        8139.0  28981.105706      25546.26         13.08     106.61  
3        8685.0   8189.976022      11367.89         24.68     100.35  
4       19693.0   7566.719898      16251.96         26.85     101.67  
..          ...           ...           ...           ...        ...  
336     10616.0   2821.000000       2699.74         22.24     102.79  
337      6594.0   1851.000000       1234.21         28.99     102.39  
338      1365.0   2384.000000        355.93         30.44     101.61  
339      1549.0   2215.000000        475.00         32.39     103.71  
340      5387.0   2100.000000       1421.38         29.12     103.14  

[341 rows x 17 columns]

In [8]:
divorce=df_sum.pivot(index='reg',columns='Year',values='divorce_rate')

In [12]:
divorce.dropna(axis=1,inplace=True)

In [13]:
divorce

Year          2010  2011  2012  2013      2014      2015      2016      2017  \
reg                                                                            
上海市       2.082899  3.39  2.22  2.88  2.540060  2.758261  3.407700  2.430757   
云南省       1.504481  1.64  1.76  1.95  2.137418  2.300148  2.515815  2.656101   
内蒙古自治区    2.312185  2.72  2.83  3.23  3.535129  3.659219  3.915032  3.997861   
北京市       2.367564  3.45  2.35  3.06  3.076270  3.785997  4.893282  3.711832   
吉林省       3.426810  3.72  4.03  4.51  4.438247  4.628042  4.711735  4.904404   
四川省       2.723365  2.57  3.11  3.31  3.384854  3.488335  3.612125  3.763994   
天津市       2.373934  3.24  2.57  3.07  2.977565  3.356884  4.236537  3.775441   
宁夏回族自治区   1.907548  2.08  2.32  2.43  2.404749  2.636047  2.924785  3.268828   
安徽省       1.820030  1.75  2.23  2.59  2.823730  2.949333  3.538523  3.888925   
山东省       1.763024  1.90  2.03  2.31  2.398660  2.446766  2.579095  2.731429   
山西省       1.228313  1.37  1.46  1.68  1.802285  1.970715  2.087870  2.226733   
广东省       1.234750  1.66  1.47  1.66  1.665528  1.782284  1.950541  1.987938   
广西壮族自治区   1.542362  1.45  1.83  1.97  2.130666  2.177085  2.351293  2.468970   
新疆维吾尔自治区  4.512241  4.81  4.62  4.82  4.735895  4.312881  3.984840  3.071567   
江苏省       2.040902  2.23  2.29  2.73  2.746115  2.874636  3.274774  3.591602   
江西省       1.461593  1.49  1.68  1.90  1.972903  2.084166  2.236353  2.405557   
河北省       2.038234  2.14  2.35  2.44  2.524007  2.680781  2.964265  3.100547   
河南省       1.418555  1.28  1.70  2.23  2.449421  2.661118  2.925538  3.316442   
浙江省       2.089161  2.43  2.24  2.41  2.468163  2.519949  2.650856  2.804748   
海南省       1.038888  1.22  1.36  1.47  1.568970  1.661581  1.826970  1.933478   
湖北省       2.026570  2.03  2.35  2.60  2.710202  2.851777  3.129955  3.381251   
湖南省       2.126987  2.09  2.34  2.50  2.621166  2.667315  2.853430  3.034425   
甘肃省       1.094843  1.13  1.28  1.49  1.632760  1.776346  1.935305  2.067876   
福建省       1.657861  1.89  2.00  2.19  2.303140  2.325762  2.508802  2.721696   
西藏自治区     0.669208  0.68  0.43  0.57  0.838641  0.732716  1.075165  1.204790   
贵州省       1.824417  1.72  2.33  2.45  2.730683  3.070680  3.427448  3.768886   
辽宁省       2.937161  3.27  3.22  3.47  3.478305  3.476677  3.651606  3.814268   
重庆市       3.934801  3.74  4.27  4.50  4.448250  4.551740  4.603739  4.927029   
陕西省       1.715382  1.76  1.89  2.14  2.258407  2.565225  2.673602  2.844561   
青海省       1.427590  1.70  1.86  1.87  2.161366  2.172279  2.576983  2.757011   
黑龙江省      3.603414  3.89  4.09  4.65  4.884833  4.979066  4.905303  5.190564   

Year          2018  
reg                 
上海市       2.438029  
云南省       2.767312  
内蒙古自治区    3.902405  
北京市       3.427825  
吉林省       4.752945  
四川省       3.756066  
天津市       4.111147  
宁夏回族自治区   3.332287  
安徽省       3.877109  
山东省       2.737705  
山西省       2.358841  
广东省       2.032513  
广西壮族自治区   2.622689  
新疆维吾尔自治区  2.413824  
江苏省       3.542550  
江西省       2.699909  
河北省       3.110862  
河南省       3.402526  
浙江省       2.705880  
海南省       2.104692  
湖北省       3.401472  
湖南省       3.099298  
甘肃省       2.196623  
福建省       2.723994  
西藏自治区     1.370113  
贵州省       4.224457  
辽宁省       3.951422  
重庆市       4.963452  
陕西省       3.336494  
青海省       2.848580  
黑龙江省      5.123939

In [14]:
pcafit=PCA(n_components=8)

In [15]:
PCA_div=pcafit.fit_transform(divorce)

In [17]:
pcafit.explained_variance_ratio_

array([8.95784802e-01, 7.72338476e-02, 1.94037885e-02, 3.92904072e-03,
       1.36592024e-03, 8.95452250e-04, 6.52705819e-04, 4.42378393e-04])

In [18]:
pcafit.explained_variance_

array([7.07161717e+00, 6.09709164e-01, 1.53179830e-01, 3.10171279e-02,
       1.07830195e-02, 7.06899189e-03, 5.15267246e-03, 3.49227921e-03])

In [19]:
pcafit2=PCA(n_components=1)

In [85]:
len(pcafit.components_)

8

In [20]:
PCA_div=pcafit2.fit_transform(divorce)

In [22]:
print(pcafit2.explained_variance_ratio_)
print(pcafit2.explained_variance_)
print(pcafit2.get_params)

[0.8957848]
[7.07161717]
<bound method BaseEstimator.get_params of PCA(n_components=1)>


In [23]:

pcafit2.components_

array([[0.31164182, 0.3341025 , 0.33826653, 0.36833014, 0.35207155,
        0.35414902, 0.34281979, 0.31310986, 0.27608778]])

In [83]:
len(pcafit2.components_[0])

9

In [92]:
pcafit2.singular_values_ 

array([14.56531891])

In [27]:
X_cov = pcafit2.get_covariance() 
print(X_cov)

[[0.7796507  0.7255914  0.73463468 0.79992569 0.7646159  0.76912767
  0.74452326 0.68000036 0.59959717]
 [0.7255914  0.8807249  0.78758136 0.85757804 0.8197234  0.82456034
  0.79818264 0.72900943 0.64281141]
 [0.73463468 0.78758136 0.90023583 0.86826631 0.82993987 0.8348371
  0.80813064 0.73809531 0.65082298]
 [0.79992569 0.85757804 0.86826631 1.04827249 0.90370119 0.90903366
  0.87995365 0.80369389 0.70866519]
 [0.7646159  0.8197234  0.82993987 0.90370119 0.9666492  0.8689077
  0.84111132 0.76821777 0.67738376]
 [0.76912767 0.82456034 0.8348371  0.90903366 0.8689077  0.97687345
  0.84607447 0.77275079 0.6813808 ]
 [0.74452326 0.79818264 0.80813064 0.87995365 0.84111132 0.84607447
  0.92184712 0.74803048 0.65958342]
 [0.68000036 0.72900943 0.73809531 0.80369389 0.76821777 0.77275079
  0.74803048 0.78604222 0.60242168]
 [0.59959717 0.64281141 0.65082298 0.70866519 0.67738376 0.6813808
  0.65958342 0.60242168 0.63402999]]


In [28]:
pcafit2.components_

array([[0.31164182, 0.3341025 , 0.33826653, 0.36833014, 0.35207155,
        0.35414902, 0.34281979, 0.31310986, 0.27608778]])

In [30]:
divorce['divorce_pca_score']=PCA_div

In [31]:
divorce

Year          2010  2011  2012  2013      2014      2015      2016      2017  \
reg                                                                            
上海市       2.082899  3.39  2.22  2.88  2.540060  2.758261  3.407700  2.430757   
云南省       1.504481  1.64  1.76  1.95  2.137418  2.300148  2.515815  2.656101   
内蒙古自治区    2.312185  2.72  2.83  3.23  3.535129  3.659219  3.915032  3.997861   
北京市       2.367564  3.45  2.35  3.06  3.076270  3.785997  4.893282  3.711832   
吉林省       3.426810  3.72  4.03  4.51  4.438247  4.628042  4.711735  4.904404   
四川省       2.723365  2.57  3.11  3.31  3.384854  3.488335  3.612125  3.763994   
天津市       2.373934  3.24  2.57  3.07  2.977565  3.356884  4.236537  3.775441   
宁夏回族自治区   1.907548  2.08  2.32  2.43  2.404749  2.636047  2.924785  3.268828   
安徽省       1.820030  1.75  2.23  2.59  2.823730  2.949333  3.538523  3.888925   
山东省       1.763024  1.90  2.03  2.31  2.398660  2.446766  2.579095  2.731429   
山西省       1.228313  1.37  1.46  1.68  1.802285  1.970715  2.087870  2.226733   
广东省       1.234750  1.66  1.47  1.66  1.665528  1.782284  1.950541  1.987938   
广西壮族自治区   1.542362  1.45  1.83  1.97  2.130666  2.177085  2.351293  2.468970   
新疆维吾尔自治区  4.512241  4.81  4.62  4.82  4.735895  4.312881  3.984840  3.071567   
江苏省       2.040902  2.23  2.29  2.73  2.746115  2.874636  3.274774  3.591602   
江西省       1.461593  1.49  1.68  1.90  1.972903  2.084166  2.236353  2.405557   
河北省       2.038234  2.14  2.35  2.44  2.524007  2.680781  2.964265  3.100547   
河南省       1.418555  1.28  1.70  2.23  2.449421  2.661118  2.925538  3.316442   
浙江省       2.089161  2.43  2.24  2.41  2.468163  2.519949  2.650856  2.804748   
海南省       1.038888  1.22  1.36  1.47  1.568970  1.661581  1.826970  1.933478   
湖北省       2.026570  2.03  2.35  2.60  2.710202  2.851777  3.129955  3.381251   
湖南省       2.126987  2.09  2.34  2.50  2.621166  2.667315  2.853430  3.034425   
甘肃省       1.094843  1.13  1.28  1.49  1.632760  1.776346  1.935305  2.067876   
福建省       1.657861  1.89  2.00  2.19  2.303140  2.325762  2.508802  2.721696   
西藏自治区     0.669208  0.68  0.43  0.57  0.838641  0.732716  1.075165  1.204790   
贵州省       1.824417  1.72  2.33  2.45  2.730683  3.070680  3.427448  3.768886   
辽宁省       2.937161  3.27  3.22  3.47  3.478305  3.476677  3.651606  3.814268   
重庆市       3.934801  3.74  4.27  4.50  4.448250  4.551740  4.603739  4.927029   
陕西省       1.715382  1.76  1.89  2.14  2.258407  2.565225  2.673602  2.844561   
青海省       1.427590  1.70  1.86  1.87  2.161366  2.172279  2.576983  2.757011   
黑龙江省      3.603414  3.89  4.09  4.65  4.884833  4.979066  4.905303  5.190564   

Year          2018  divorce_pca_score  
reg                                    
上海市       2.438029           0.021476  
云南省       2.767312          -1.689898  
内蒙古自治区    3.902405           1.942646  
北京市       3.427825           1.976942  
吉林省       4.752945           4.954361  
四川省       3.756066           1.813955  
天津市       4.111147           1.783573  
宁夏回族自治区   3.332287          -0.349938  
安徽省       3.877109           0.354462  
山东省       2.737705          -1.117522  
山西省       2.358841          -2.695681  
广东省       2.032513          -2.927593  
广西壮族自治区   2.622689          -1.911409  
新疆维吾尔自治区  2.413824           4.494861  
江苏省       3.542550           0.325866  
江西省       2.699909          -2.126130  
河北省       3.110862          -0.317792  
河南省       3.402526          -0.993837  
浙江省       2.705880          -0.641781  
海南省       2.104692          -3.359058  
湖北省       3.401472           0.051793  
湖南省       3.099298          -0.320575  
甘肃省       2.196623          -3.223680  
福建省       2.723994          -1.315398  
西藏自治区     1.370113          -5.575552  
贵州省       4.224457           0.358517  
辽宁省       3.951422           2.322581  
重庆市       4.963452           5.201534  
陕西省       3.336494          -1.063404  
青海省       2.848580          -1.651305  
黑龙江省      5.123939           5.677988

In [95]:
divorce.to_excel("divorce_cluster.xlsx")

In [61]:
divorce=pd.read_excel("divorce_cluster.xlsx")

In [62]:
divorce

reg      2010  2011  2012  2013      2014      2015      2016      2017  \
0    上海  2.082899  3.39  2.22  2.88  2.540060  2.758261  3.407700  2.430757   
1    云南  1.504481  1.64  1.76  1.95  2.137418  2.300148  2.515815  2.656101   
2   内蒙古  2.312185  2.72  2.83  3.23  3.535129  3.659219  3.915032  3.997861   
3    北京  2.367564  3.45  2.35  3.06  3.076270  3.785997  4.893282  3.711832   
4    吉林  3.426810  3.72  4.03  4.51  4.438247  4.628042  4.711735  4.904404   
5    四川  2.723365  2.57  3.11  3.31  3.384854  3.488335  3.612125  3.763994   
6    天津  2.373934  3.24  2.57  3.07  2.977565  3.356884  4.236537  3.775441   
7    宁夏  1.907548  2.08  2.32  2.43  2.404749  2.636047  2.924785  3.268828   
8    安徽  1.820030  1.75  2.23  2.59  2.823730  2.949333  3.538523  3.888925   
9    山东  1.763024  1.90  2.03  2.31  2.398660  2.446766  2.579095  2.731429   
10   山西  1.228313  1.37  1.46  1.68  1.802285  1.970715  2.087870  2.226733   
11   广东  1.234750  1.66  1.47  1.66  1.665528  1.782284  1.950541  1.987938   
12   广西  1.542362  1.45  1.83  1.97  2.130666  2.177085  2.351293  2.468970   
13   新疆  4.512241  4.81  4.62  4.82  4.735895  4.312881  3.984840  3.071567   
14   江苏  2.040902  2.23  2.29  2.73  2.746115  2.874636  3.274774  3.591602   
15   江西  1.461593  1.49  1.68  1.90  1.972903  2.084166  2.236353  2.405557   
16   河北  2.038234  2.14  2.35  2.44  2.524007  2.680781  2.964265  3.100547   
17   河南  1.418555  1.28  1.70  2.23  2.449421  2.661118  2.925538  3.316442   
18   浙江  2.089161  2.43  2.24  2.41  2.468163  2.519949  2.650856  2.804748   
19   海南  1.038888  1.22  1.36  1.47  1.568970  1.661581  1.826970  1.933478   
20   湖北  2.026570  2.03  2.35  2.60  2.710202  2.851777  3.129955  3.381251   
21   湖南  2.126987  2.09  2.34  2.50  2.621166  2.667315  2.853430  3.034425   
22   甘肃  1.094843  1.13  1.28  1.49  1.632760  1.776346  1.935305  2.067876   
23   福建  1.657861  1.89  2.00  2.19  2.303140  2.325762  2.508802  2.721696   
24   西藏  0.669208  0.68  0.43  0.57  0.838641  0.732716  1.075165  1.204790   
25   贵州  1.824417  1.72  2.33  2.45  2.730683  3.070680  3.427448  3.768886   
26   辽宁  2.937161  3.27  3.22  3.47  3.478305  3.476677  3.651606  3.814268   
27   重庆  3.934801  3.74  4.27  4.50  4.448250  4.551740  4.603739  4.927029   
28   陕西  1.715382  1.76  1.89  2.14  2.258407  2.565225  2.673602  2.844561   
29   青海  1.427590  1.70  1.86  1.87  2.161366  2.172279  2.576983  2.757011   
30  黑龙江  3.603414  3.89  4.09  4.65  4.884833  4.979066  4.905303  5.190564   

        2018   meanCDR  divorce_pca_score  
0   2.438029  2.683078           0.021476  
1   2.767312  2.136808          -1.689898  
2   3.902405  3.344648           1.942646  
3   3.427825  3.346975           1.976942  
4   4.752945  4.346909           4.954361  
5   3.756066  3.302082           1.813955  
6   4.111147  3.301279           1.783573  
7   3.332287  2.589360          -0.349938  
8   3.877109  2.829739           0.354462  
9   2.737705  2.321853          -1.117522  
10  2.358841  1.798306          -2.695681  
11  2.032513  1.715950          -2.927593  
12  2.622689  2.060341          -1.911409  
13  2.413824  4.142361           4.494861  
14  3.542550  2.813398           0.325866  
15  2.699909  1.992276          -2.126130  
16  3.110862  2.594300          -0.317792  
17  3.402526  2.375956          -0.993837  
18  2.705880  2.479862          -0.641781  
19  2.104692  1.576064          -3.359058  
20  3.401472  2.720136           0.051793  
21  3.099298  2.592514          -0.320575  
22  2.196623  1.622639          -3.223680  
23  2.723994  2.257917          -1.315398  
24  1.370113  0.841181          -5.575552  
25  4.224457  2.838508           0.358517  
26  3.951422  3.474382           2.322581  
27  4.963452  4.437668           5.201534  
28  3.336494  2.353741          -1.063404  
29  2.848580  2.152645          -1.651305  
30  5.123939  4.590791           5.677988

In [93]:
province=list(divorce['reg'])
CDR=list(divorce['divorce_pca_score'])
total=[list(z) for z in zip(province,CDR)]
list1=[[province[i],CDR[i]] for i in range(len(province))]    

In [94]:
import re
import jieba
import numpy as np
import pandas as pd

from collections import Counter
import pandas as pd
from pyecharts.charts import Map
from pyecharts import options as opts
from pyecharts.charts import Timeline
map1= Map(init_opts=opts.InitOpts(width='800px',height='600px'))
map1.add("", list1, maptype='china',is_map_symbol_show=False)
map1.set_global_opts(
    title_opts=opts.TitleOpts("China Crude Divorce Rate PCA Distribution",pos_left='center'),
    visualmap_opts=opts.VisualMapOpts(max_=max(CDR),min_=min(CDR),is_piecewise=False),
    legend_opts=opts.LegendOpts(is_show=False)
)
map1.render("China Crude Divorce Rate PCA Distribution.html")

'E:\\pythoncode\\final work\\China Crude Divorce Rate PCA Distribution.html'

In [37]:
CDR

[0.02147635107868145,
 -1.689898046119253,
 1.942645517152011,
 1.976941574613748,
 4.954360664702762,
 1.813955164670005,
 1.783573449748307,
 -0.3499384799878268,
 0.3544623663388689,
 -1.117522149643555,
 -2.695680795566619,
 -2.927593443614868,
 -1.911409373959207,
 4.494861259213475,
 0.3258663250774082,
 -2.126130313665385,
 -0.3177920100874779,
 -0.9938369991857484,
 -0.6417814697261828,
 -3.359058292955114,
 0.05179303204591931,
 -0.3205754929063033,
 -3.223679789408584,
 -1.315398022437522,
 -5.575552349502307,
 0.3585168379623072,
 2.322581200038464,
 5.201533716665013,
 -1.063403904141776,
 -1.651304746491784,
 5.677988220092508]

In [89]:
province=list(divorce['reg'])
CDR=list(divorce['meanCDR'])
total=[list(z) for z in zip(province,CDR)]
list1=[[province[i],CDR[i]] for i in range(len(province))]
import re
import jieba
import numpy as np
import pandas as pd

from collections import Counter
import pandas as pd
from pyecharts.charts import Map
from pyecharts import options as opts
from pyecharts.charts import Timeline
map1= Map(init_opts=opts.InitOpts(width='800px',height='600px'))
map1.add("", list1, maptype='china',is_map_symbol_show=False)
map1.set_global_opts(
    title_opts=opts.TitleOpts("China Mean Crude Divorce Rate(2010-2018)",pos_left='center'),
    visualmap_opts=opts.VisualMapOpts(max_=max(CDR),min_=min(CDR),is_piecewise=False),
    legend_opts=opts.LegendOpts(is_show=False)
)
map1.render("China Mean Crude Divorce Rate.html")

'E:\\pythoncode\\final work\\China Mean Crude Divorce Rate.html'

In [66]:
from sklearn.cluster import KMeans
num_clusters = 4
km_cluster = KMeans(n_clusters=num_clusters, max_iter=300, n_init=40,init='k-means++')
result = km_cluster.fit_predict(divorce.drop(["divorce_pca_score","meanCDR","reg"],axis=1))

print(result)

[1 1 3 3 2 3 3 1 1 1 0 0 0 2 1 0 1 1 1 0 1 1 0 1 0 1 3 2 1 1 2]


In [76]:
result=[1,1,2,2,3,2,2,1,1,1,0,0 ,0, 3 ,1, 0 ,1 ,1, 1 ,0 ,1, 1, 0, 1, 0 ,1, 2, 3, 1 ,1, 3]



In [77]:
divorce["c_r1"]=result

In [69]:
from sklearn.cluster import KMeans
num_clusters = 5
km_cluster = KMeans(n_clusters=num_clusters, max_iter=300, n_init=40,init='k-means++')
result = km_cluster.fit_predict(divorce.drop(["divorce_pca_score","meanCDR","reg","c_r1"],axis=1))

print(result)

divorce["c_r2"]=result

[2 2 0 0 4 0 0 2 2 2 1 1 1 3 2 1 2 2 2 1 2 2 1 2 1 2 0 4 2 2 4]


In [90]:
province=list(divorce['reg'])
CDR=list(divorce['c_r1'])
total=[list(z) for z in zip(province,CDR)]
list1=[[province[i],CDR[i]] for i in range(len(province))]
import re
import jieba
import numpy as np
import pandas as pd

from collections import Counter
import pandas as pd
from pyecharts.charts import Map
from pyecharts import options as opts
from pyecharts.charts import Timeline
map1= Map(init_opts=opts.InitOpts(width='800px',height='600px'))
map1.add("", list1, maptype='china',is_map_symbol_show=False)
map1.set_global_opts(
    title_opts=opts.TitleOpts("China Crude Divorce Rate Clustering_group 4(2010-2018)",pos_left='center'),
    visualmap_opts=opts.VisualMapOpts(max_=max(CDR),min_=min(CDR),is_piecewise=False),
    legend_opts=opts.LegendOpts(is_show=False)
)
map1.render("China Crude Divorce Rate Clustering (group 4).html")

'E:\\pythoncode\\final work\\China Crude Divorce Rate Clustering (group 4).html'

In [74]:
province=list(divorce['reg'])
CDR=list(divorce['c_r2'])
total=[list(z) for z in zip(province,CDR)]
list1=[[province[i],CDR[i]] for i in range(len(province))]
import re
import jieba
import numpy as np
import pandas as pd

from collections import Counter
import pandas as pd
from pyecharts.charts import Map
from pyecharts import options as opts
from pyecharts.charts import Timeline
map1= Map(init_opts=opts.InitOpts(width='1200px',height='800px'))
map1.add("", list1, maptype='china',is_map_symbol_show=False)
map1.set_global_opts(
    title_opts=opts.TitleOpts("China Crude Divorce Rate Clustering (group 5)",pos_left='center'),
    visualmap_opts=opts.VisualMapOpts(max_=max(CDR),min_=min(CDR),is_piecewise=False),
    legend_opts=opts.LegendOpts(is_show=False)
)
map1.render("China Crude Divorce Rate Clustering (group 5).html")

'E:\\pythoncode\\final work\\China Crude Divorce Rate Clustering (group 5).html'

In [81]:
divorce

reg      2010  2011  2012  2013      2014      2015      2016      2017  \
0    上海  2.082899  3.39  2.22  2.88  2.540060  2.758261  3.407700  2.430757   
1    云南  1.504481  1.64  1.76  1.95  2.137418  2.300148  2.515815  2.656101   
2   内蒙古  2.312185  2.72  2.83  3.23  3.535129  3.659219  3.915032  3.997861   
3    北京  2.367564  3.45  2.35  3.06  3.076270  3.785997  4.893282  3.711832   
4    吉林  3.426810  3.72  4.03  4.51  4.438247  4.628042  4.711735  4.904404   
5    四川  2.723365  2.57  3.11  3.31  3.384854  3.488335  3.612125  3.763994   
6    天津  2.373934  3.24  2.57  3.07  2.977565  3.356884  4.236537  3.775441   
7    宁夏  1.907548  2.08  2.32  2.43  2.404749  2.636047  2.924785  3.268828   
8    安徽  1.820030  1.75  2.23  2.59  2.823730  2.949333  3.538523  3.888925   
9    山东  1.763024  1.90  2.03  2.31  2.398660  2.446766  2.579095  2.731429   
10   山西  1.228313  1.37  1.46  1.68  1.802285  1.970715  2.087870  2.226733   
11   广东  1.234750  1.66  1.47  1.66  1.665528  1.782284  1.950541  1.987938   
12   广西  1.542362  1.45  1.83  1.97  2.130666  2.177085  2.351293  2.468970   
13   新疆  4.512241  4.81  4.62  4.82  4.735895  4.312881  3.984840  3.071567   
14   江苏  2.040902  2.23  2.29  2.73  2.746115  2.874636  3.274774  3.591602   
15   江西  1.461593  1.49  1.68  1.90  1.972903  2.084166  2.236353  2.405557   
16   河北  2.038234  2.14  2.35  2.44  2.524007  2.680781  2.964265  3.100547   
17   河南  1.418555  1.28  1.70  2.23  2.449421  2.661118  2.925538  3.316442   
18   浙江  2.089161  2.43  2.24  2.41  2.468163  2.519949  2.650856  2.804748   
19   海南  1.038888  1.22  1.36  1.47  1.568970  1.661581  1.826970  1.933478   
20   湖北  2.026570  2.03  2.35  2.60  2.710202  2.851777  3.129955  3.381251   
21   湖南  2.126987  2.09  2.34  2.50  2.621166  2.667315  2.853430  3.034425   
22   甘肃  1.094843  1.13  1.28  1.49  1.632760  1.776346  1.935305  2.067876   
23   福建  1.657861  1.89  2.00  2.19  2.303140  2.325762  2.508802  2.721696   
24   西藏  0.669208  0.68  0.43  0.57  0.838641  0.732716  1.075165  1.204790   
25   贵州  1.824417  1.72  2.33  2.45  2.730683  3.070680  3.427448  3.768886   
26   辽宁  2.937161  3.27  3.22  3.47  3.478305  3.476677  3.651606  3.814268   
27   重庆  3.934801  3.74  4.27  4.50  4.448250  4.551740  4.603739  4.927029   
28   陕西  1.715382  1.76  1.89  2.14  2.258407  2.565225  2.673602  2.844561   
29   青海  1.427590  1.70  1.86  1.87  2.161366  2.172279  2.576983  2.757011   
30  黑龙江  3.603414  3.89  4.09  4.65  4.884833  4.979066  4.905303  5.190564   

        2018   meanCDR  divorce_pca_score  c_r1  c_r2  
0   2.438029  2.683078           0.021476     1     2  
1   2.767312  2.136808          -1.689898     1     2  
2   3.902405  3.344648           1.942646     2     0  
3   3.427825  3.346975           1.976942     2     0  
4   4.752945  4.346909           4.954361     3     4  
5   3.756066  3.302082           1.813955     2     0  
6   4.111147  3.301279           1.783573     2     0  
7   3.332287  2.589360          -0.349938     1     2  
8   3.877109  2.829739           0.354462     1     2  
9   2.737705  2.321853          -1.117522     1     2  
10  2.358841  1.798306          -2.695681     0     1  
11  2.032513  1.715950          -2.927593     0     1  
12  2.622689  2.060341          -1.911409     0     1  
13  2.413824  4.142361           4.494861     3     3  
14  3.542550  2.813398           0.325866     1     2  
15  2.699909  1.992276          -2.126130     0     1  
16  3.110862  2.594300          -0.317792     1     2  
17  3.402526  2.375956          -0.993837     1     2  
18  2.705880  2.479862          -0.641781     1     2  
19  2.104692  1.576064          -3.359058     0     1  
20  3.401472  2.720136           0.051793     1     2  
21  3.099298  2.592514          -0.320575     1     2  
22  2.196623  1.622639          -3.223680     0     1  
23  2.723994  2.257917          -1.315398     1     2  
24  1.370113  0.841181          -5.575552     0     1  
25  4.224457  2.838